// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr9LGPZp-Im0kaZMXOSPq8u4jZks1qNpA',
    appId: '1:762145535469:web:fe4a64dfa3f451e069e3e4',
    messagingSenderId: '762145535469',
    projectId: 'nice-today-weather',
    authDomain: 'nice-today-weather.firebaseapp.com',
    storageBucket: 'nice-today-weather.firebasestorage.app',
    measurementId: 'G-HW0KFKDBJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANZNzuCM5ZzDCn3mouNtKkq8iqkc3PPcU',
    appId: '1:762145535469:android:94ff8eeb418f408569e3e4',
    messagingSenderId: '762145535469',
    projectId: 'nice-today-weather',
    storageBucket: 'nice-today-weather.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApVhKpv9DT8Il_loB6oDsftWhTo9LTqE8',
    appId: '1:762145535469:ios:25c5704d8c144f3769e3e4',
    messagingSenderId: '762145535469',
    projectId: 'nice-today-weather',
    storageBucket: 'nice-today-weather.firebasestorage.app',
    androidClientId: '762145535469-d5hbt3rb9dohif3egle5abu2hjn2rcmd.apps.googleusercontent.com',
    iosClientId: '762145535469-1pg3qoesduojih4ca8ih7vo1jpdcdt5q.apps.googleusercontent.com',
    iosBundleId: 'com.nicetodayweather',
  );
}
